services:
  - type: web
    name: booking-backend
    env: python
    region: frankfurt
    plan: free
    pythonVersion: "3.12.0"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    rootDir: Backend
