"""Add username and permissions

Revision ID: 2c4e88ddec83
Revises: c2e0e1ecdf40
Create Date: 2026-01-18 19:03:45.264047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c4e88ddec83'
down_revision = 'c2e0e1ecdf40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        pass
        # batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        # batch_op.add_column(sa.Column('access_dashboard', sa.Boolean(), nullable=True))
        # batch_op.add_column(sa.Column('access_control_center', sa.Boolean(), nullable=True))

    # Populate existing data
    op.execute("UPDATE users SET username = first_name || '-' || id")
    op.execute("UPDATE users SET access_dashboard = 1")
    op.execute("UPDATE users SET access_control_center = 0")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username', nullable=False, existing_type=sa.String(length=100))
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_column('access_control_center')
        batch_op.drop_column('access_dashboard')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
