"""add email verification and reset otp fields

Revision ID: 8115a19b0894
Revises: 6f766884927e
Create Date: 2026-03-06 16:47:08.839814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8115a19b0894'
down_revision = '6f766884927e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verification_otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('reset_otp_expires_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('profile_picture',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('reset_otp_expires_at')
        batch_op.drop_column('reset_otp')
        batch_op.drop_column('otp_expires_at')
        batch_op.drop_column('verification_otp')
        batch_op.drop_column('is_email_verified')

    # ### end Alembic commands ###
