"""Update notifications and add settings

Revision ID: e680dd380b9d
Revises: 8115a19b0894
Create Date: 2026-03-09 01:19:45.142127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e680dd380b9d'
down_revision = '8115a19b0894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notify_messages', sa.Boolean(), nullable=True),
    sa.Column('notify_bookings', sa.Boolean(), nullable=True),
    sa.Column('notify_payments', sa.Boolean(), nullable=True),
    sa.Column('sound_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verification_token',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('reset_token',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('reset_token',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
        batch_op.alter_column('verification_token',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('transaction_id')

    op.drop_table('notification_settings')
    # ### end Alembic commands ###
